name: Update Wishlist

on:
  push:
    paths:
      - 'new_urls.txt'

jobs:
  update-wishlist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run update script
        run: python update_wishlist.py

      - name: Commit updated JSON
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Wishlist automatisch bijgewerkt"
          file_pattern: "wishlist.json"
          branch: main
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          github_token: ${{ secrets.GH_TOKEN }}
