name: Update Wishlist

on:
  push:
    paths:
      - 'new_urls.txt'

jobs:
  update-wishlist:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 tinyurl

      - name: Run update script
        run: python update_wishlist.py

      - name: Auto commit JSON
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: wishlist.json
          commit_message: Wishlist automatisch bijgewerkt
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
