name: Update Wishlist

on:
  push:
    paths:
      - 'new_urls.txt'

jobs:
  update-wishlist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run update script
        run: python update_wishlist.py

      - name: Commit updated JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add wishlist.json
          git diff --cached --quiet || git commit -m "Wishlist automatisch bijgewerkt"
          git push origin main
