name: Update Wishlist

on:
  push:
    paths:
      - 'new_urls.txt'

jobs:
  update-wishlist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run update script
        run: python update_wishlist.py

      - name: Commit updated JSON
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "ThijmenBot"
          git config --global user.email "thijmenbot@users.noreply.github.com"
          git add wishlist.json
          if ! git diff --cached --quiet; then
            git commit -m "Wishlist automatisch bijgewerkt"
            git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          else
            echo "Geen wijzigingen, commit overgeslagen"
          fi

            echo "Geen wijzigingen, commit overgeslagen"
          fi

